add_newline = true

[character]
success_symbol = "[ï€Œ](bold green)"
error_symbol = "[ï€](bold red)"

[python]
symbol = "îˆµ "

[cmake]
symbol = "î˜	"

[git_status]
conflicted = "ğŸ³"
ahead = "ğŸğŸ’¨"
behind = "ğŸ˜°"
diverged = "ğŸ˜µ"
untracked = "ğŸ¤·â€"
stashed = "ğŸ“¦"
modified = "ğŸ“"
staged.value = "++"
staged.style = "green"
renamed = "ğŸ‘…"
deleted = "ğŸ—‘"
